export const getCountryFlag = (countryName: string): string => {
  const countryFlags: Record<string, string> = {
    'England': '🏴󠁧󠁢󠁥󠁮󠁧󠁿',
    'Spain': '🇪🇸',
    'Germany': '🇩🇪',
    'Italy': '🇮🇹',
    'France': '🇫🇷',
    'Portugal': '🇵🇹',
    'Netherlands': '🇳🇱',
    'Belgium': '🇧🇪',
    'Turkey': '🇹🇷',
    'Scotland': '🏴󠁧󠁢󠁳󠁣󠁴󠁿',
    'Austria': '🇦🇹',
    'Switzerland': '🇨🇭',
    'Denmark': '🇩🇰',
    'Sweden': '🇸🇪',
    'Norway': '🇳🇴',
    'Poland': '🇵🇱',
    'Czech Republic': '🇨🇿',
    'Czechia': '🇨🇿',
    'Greece': '🇬🇷',
    'Croatia': '🇭🇷',
    'Serbia': '🇷🇸',
    'Ukraine': '🇺🇦',
    'Russia': '🇷🇺',
    'Brazil': '🇧🇷',
    'Argentina': '🇦🇷',
    'USA': '🇺🇸',
    'Mexico': '🇲🇽',
    'Japan': '🇯🇵',
    'South Korea': '🇰🇷',
    'Korea Republic': '🇰🇷',
    'Australia': '🇦🇺',
    'Saudi Arabia': '🇸🇦',
    'United Arab Emirates': '🇦🇪',
    'China': '🇨🇳',
    'India': '🇮🇳',
    'Egypt': '🇪🇬',
    'South Africa': '🇿🇦',
    'Morocco': '🇲🇦',
    'Algeria': '🇩🇿',
    'Tunisia': '🇹🇳',
    'Israel': '🇮🇱',
    'Canada': '🇨🇦',
    'Chile': '🇨🇱',
    'Colombia': '🇨🇴',
    'Uruguay': '🇺🇾',
    'Paraguay': '🇵🇾',
    'Ecuador': '🇪🇨',
    'Peru': '🇵🇪',
    'Venezuela': '🇻🇪',
    'Bolivia': '🇧🇴',
    'Romania': '🇷🇴',
    'Bulgaria': '🇧🇬',
    'Hungary': '🇭🇺',
    'Slovakia': '🇸🇰',
    'Slovenia': '🇸🇮',
    'Republic of Ireland': '🇮🇪',
    'Ireland': '🇮🇪',
    'Northern Ireland': '🇬🇧',
    'Wales': '🏴󠁧󠁢󠁷󠁬󠁳󠁿',
    'Finland': '🇫🇮',
    'Iceland': '🇮🇸',
    'Luxembourg': '🇱🇺',
    'Cyprus': '🇨🇾',
    'Malta': '🇲🇹',
    'Albania': '🇦🇱',
    'Bosnia and Herzegovina': '🇧🇦',
    'Montenegro': '🇲🇪',
    'North Macedonia': '🇲🇰',
    'Kosovo': '🇽🇰',
    'Lithuania': '🇱🇹',
    'Latvia': '🇱🇻',
    'Estonia': '🇪🇪',
    'Belarus': '🇧🇾',
    'Moldova': '🇲🇩',
    'Georgia': '🇬🇪',
    'Armenia': '🇦🇲',
    'Azerbaijan': '🇦🇿',
    'Kazakhstan': '🇰🇿',
    'Uzbekistan': '🇺🇿',
    'Qatar': '🇶🇦',
    'Kuwait': '🇰🇼',
    'Bahrain': '🇧🇭',
    'Oman': '🇴🇲',
    'Iraq': '🇮🇶',
    'Iran': '🇮🇷',
    'Lebanon': '🇱🇧',
    'Jordan': '🇯🇴',
    'Palestine': '🇵🇸',
    'Syria': '🇸🇾',
    'Vietnam': '🇻🇳',
    'Thailand': '🇹🇭',
    'Malaysia': '🇲🇾',
    'Singapore': '🇸🇬',
    'Indonesia': '🇮🇩',
    'Philippines': '🇵🇭',
    'New Zealand': '🇳🇿',
    'World': '🌍',
    'Europe': '🇪🇺',
  };
  return countryFlags[countryName] || '🌍';
};
